language: cpp
sudo: false

os:
  - linux
#  - osx https://docs.travis-ci.com/user/multi-os/

compiler: 
 - gcc
  
addons:
  apt:
    packages:
      - graphviz
      - libboost-all-dev
#    sources:
#      - george-edison55/cmake-3.x

install:
  # Freely inspired from https://github.com/boostorg/hana/blob/master/.travis.yml
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake
    fi
  ############################################################################
  # Install a recent Doxygen
  ############################################################################
  - |
    DOXYGEN_URL="http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.10.linux.bin.tar.gz"
    mkdir doxygen && travis_retry wget --quiet -O - ${DOXYGEN_URL} | tar --strip-components=1 -xz -C doxygen
    export PATH=${DEPS_DIR}/doxygen/bin:${PATH}
  ############################################################################
  # Back to ${TRAVIS_BUILD_DIR}
  ############################################################################
  - cd ${TRAVIS_BUILD_DIR}

script:
 - cmake --version
 - mkdir build 
 - mkdir install
 - cd build 
 - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=${PWD}../install .. 
 - make -j 
 - make doc 
 - make test 
 - make install
 
notifications:
  email: true
 
